# Generated by Django 3.2.3 on 2021-05-23 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KVPairTable',
            fields=[
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('uuid_val', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
